# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

- task: SoapUIProForAzureDevOpsTask@2
  inputs:
    project: 'https://github.com/priteshak/POC/blob/master/calculatorDemo-soapui-project.xml'
    rootFolder: '$(Common.TestResultsDirectory)'
