trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    sudo apt-get update
    sudo apt-get install -y openjdk-11-jdk
    java -version
  displayName: 'Set up Java 11'

- script: |
    mvn clean install
  displayName: 'Build with Maven'

- task: SoapUIProForAzureDevOpsTask@2
  inputs:
    project: '$(System.DefaultWorkingDirectory)/POC/calculatorDemo-soapui-project.xml'
    rootFolder: '$(Common.TestResultsDirectory)'

- script: |
    echo "Common Test Results Directory: $(Common.TestResultsDirectory)"
    ls -la $(Common.TestResultsDirectory)
  displayName: 'Show Test Results Directory'
